/**
 * A real 299-heartbeat session (see README) used as the default "realistic working
 * state" shown on first load, and reloadable any time from the Sample data tab.
 * Shaped exactly like a raw export — deliberately untyped, and run through
 * {@link normalizeHeartbeats} like any uploaded file rather than pre-normalized.
 */
export const SAMPLE_RAW: unknown = {
  "sampleId": "sample-01",
  "heartbeatCount": 299,
  "durationSeconds": 52291.673,
  "heartbeats": [
    {
      "t": 0,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 60.093,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 117.363,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 122.62,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 140.586,
      "write": false,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 144.714,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 32974.083,
      "write": false,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 33031.939,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-3.output",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 25,
      "sourceType": "direct_entry"
    },
    {
      "t": 33124.929,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-3.output",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 25,
      "sourceType": "direct_entry"
    },
    {
      "t": 33187.419,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-3.output",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 25,
      "sourceType": "direct_entry"
    },
    {
      "t": 33255.263,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-3.output",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 25,
      "sourceType": "direct_entry"
    },
    {
      "t": 33273.175,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-4.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 211,
      "sourceType": "direct_entry"
    },
    {
      "t": 33290.019,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-4.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 211,
      "sourceType": "direct_entry"
    },
    {
      "t": 33351.585,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-4.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 211,
      "sourceType": "direct_entry"
    },
    {
      "t": 33412.278,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-4.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 211,
      "sourceType": "direct_entry"
    },
    {
      "t": 33456.86,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-5.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 233,
      "sourceType": "direct_entry"
    },
    {
      "t": 33504.966,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-5.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 233,
      "sourceType": "direct_entry"
    },
    {
      "t": 33509.384,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-4.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 211,
      "sourceType": "direct_entry"
    },
    {
      "t": 33581.758,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-4.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 211,
      "sourceType": "direct_entry"
    },
    {
      "t": 33641.901,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-4.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 211,
      "sourceType": "direct_entry"
    },
    {
      "t": 33668.219,
      "write": false,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 33685.807,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 33690.603,
      "write": false,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 33717.997,
      "write": false,
      "project": "project-1",
      "language": "HTML",
      "file": "file-6.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 449,
      "sourceType": "direct_entry"
    },
    {
      "t": 33739.605,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 33832.338,
      "write": false,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 34843.808,
      "write": false,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 34861.48,
      "write": false,
      "project": "project-1",
      "language": "Markdown",
      "file": "file-7.md",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 157,
      "sourceType": "direct_entry"
    },
    {
      "t": 34947.814,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 34951.504,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 34961.624,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 34968.411,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 34984.543,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 34995.233,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 34998.454,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35009.869,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35015.556,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35018.806,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35023.261,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35033.489,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35040.847,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35044.015,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35047.109,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35056.26,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35059.602,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35099.318,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35104.075,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35109.912,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35171.597,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35232.218,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35317.684,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 35342.481,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-8.output",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 1074,
      "sourceType": "direct_entry"
    },
    {
      "t": 35357.033,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-9.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 69,
      "sourceType": "direct_entry"
    },
    {
      "t": 35430.276,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-9.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 69,
      "sourceType": "direct_entry"
    },
    {
      "t": 35478.611,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-10.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 19,
      "sourceType": "direct_entry"
    },
    {
      "t": 35511.605,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-9.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 69,
      "sourceType": "direct_entry"
    },
    {
      "t": 35691.028,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-8.output",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 1074,
      "sourceType": "direct_entry"
    },
    {
      "t": 35695.174,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-8.output",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 1074,
      "sourceType": "direct_entry"
    },
    {
      "t": 35767.999,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-8.output",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 1074,
      "sourceType": "direct_entry"
    },
    {
      "t": 35770.908,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-11.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 99,
      "sourceType": "direct_entry"
    },
    {
      "t": 35793.516,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-11.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 99,
      "sourceType": "direct_entry"
    },
    {
      "t": 35855.14,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-11.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 99,
      "sourceType": "direct_entry"
    },
    {
      "t": 35922.347,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-11.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 99,
      "sourceType": "direct_entry"
    },
    {
      "t": 35991.278,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-11.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 99,
      "sourceType": "direct_entry"
    },
    {
      "t": 36016.832,
      "write": false,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 36044.938,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 36055.867,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 36064.817,
      "write": false,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 36083.301,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 36093.145,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 36141.714,
      "write": false,
      "project": "project-1",
      "language": "Markdown",
      "file": "file-12.md",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 165,
      "sourceType": "direct_entry"
    },
    {
      "t": 36152.202,
      "write": false,
      "project": "project-1",
      "language": "Markdown",
      "file": "file-12.md",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 165,
      "sourceType": "direct_entry"
    },
    {
      "t": 39479.432,
      "write": false,
      "project": "project-1",
      "language": "Markdown",
      "file": "file-12.md",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 165,
      "sourceType": "direct_entry"
    },
    {
      "t": 39492.196,
      "write": false,
      "project": "project-1",
      "language": "Markdown",
      "file": "file-13.md",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 278,
      "sourceType": "direct_entry"
    },
    {
      "t": 39516.922,
      "write": false,
      "project": "project-1",
      "language": "Prisma",
      "file": "file-14.prisma",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 344,
      "sourceType": "direct_entry"
    },
    {
      "t": 39528.226,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-15.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 34,
      "sourceType": "direct_entry"
    },
    {
      "t": 39537.853,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-16.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 541,
      "sourceType": "direct_entry"
    },
    {
      "t": 39567.28,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-15.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 211,
      "sourceType": "direct_entry"
    },
    {
      "t": 39604.941,
      "write": false,
      "project": "project-1",
      "language": "Prisma",
      "file": "file-14.prisma",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 344,
      "sourceType": "direct_entry"
    },
    {
      "t": 39611.094,
      "write": true,
      "project": "project-1",
      "language": "Prisma",
      "file": "file-14.prisma",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 344,
      "sourceType": "direct_entry"
    },
    {
      "t": 39647.842,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-15.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 34,
      "sourceType": "direct_entry"
    },
    {
      "t": 39651.32,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-15.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 34,
      "sourceType": "direct_entry"
    },
    {
      "t": 39656,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-15.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 34,
      "sourceType": "direct_entry"
    },
    {
      "t": 39662.834,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 39676.771,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 39685.638,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 39692.938,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 39714.243,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 39727.444,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 39796.63,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-1.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 957,
      "sourceType": "direct_entry"
    },
    {
      "t": 39802.006,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-8.output",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 1074,
      "sourceType": "direct_entry"
    },
    {
      "t": 39809.456,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-8.output",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 1074,
      "sourceType": "direct_entry"
    },
    {
      "t": 39870.693,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-8.output",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 1074,
      "sourceType": "direct_entry"
    },
    {
      "t": 39916.053,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-16.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 541,
      "sourceType": "direct_entry"
    },
    {
      "t": 39921.175,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-16.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 541,
      "sourceType": "direct_entry"
    },
    {
      "t": 39928.946,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-16.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 541,
      "sourceType": "direct_entry"
    },
    {
      "t": 39932.509,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-16.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 541,
      "sourceType": "direct_entry"
    },
    {
      "t": 39941.274,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-17.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 197,
      "sourceType": "direct_entry"
    },
    {
      "t": 39945.226,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-18.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 90,
      "sourceType": "direct_entry"
    },
    {
      "t": 39948.729,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-19.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 183,
      "sourceType": "direct_entry"
    },
    {
      "t": 39951.665,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-20.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 171,
      "sourceType": "direct_entry"
    },
    {
      "t": 39963.237,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-21.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 342,
      "sourceType": "direct_entry"
    },
    {
      "t": 39967.748,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-21.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 342,
      "sourceType": "direct_entry"
    },
    {
      "t": 39980.96,
      "write": true,
      "project": "project-1",
      "language": "JSON",
      "file": "file-22.json",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 75,
      "sourceType": "direct_entry"
    },
    {
      "t": 39999.047,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-23.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 127,
      "sourceType": "direct_entry"
    },
    {
      "t": 40011.013,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-24.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 79,
      "sourceType": "direct_entry"
    },
    {
      "t": 40027.988,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-25.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 110,
      "sourceType": "direct_entry"
    },
    {
      "t": 40051.521,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-26.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 126,
      "sourceType": "direct_entry"
    },
    {
      "t": 40067.524,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-27.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 367,
      "sourceType": "direct_entry"
    },
    {
      "t": 40072.022,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-26.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 126,
      "sourceType": "direct_entry"
    },
    {
      "t": 40088.444,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-28.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 66,
      "sourceType": "direct_entry"
    },
    {
      "t": 40122.732,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-20.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 171,
      "sourceType": "direct_entry"
    },
    {
      "t": 40132.449,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-20.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 171,
      "sourceType": "direct_entry"
    },
    {
      "t": 40138.485,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-20.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 171,
      "sourceType": "direct_entry"
    },
    {
      "t": 40143.99,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-20.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 171,
      "sourceType": "direct_entry"
    },
    {
      "t": 40187.277,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-29.mts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 20,
      "sourceType": "direct_entry"
    },
    {
      "t": 40279.103,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-29.mts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 20,
      "sourceType": "direct_entry"
    },
    {
      "t": 40349.815,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 40416.181,
      "write": false,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 42551.314,
      "write": false,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 42559.928,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-30.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 113,
      "sourceType": "direct_entry"
    },
    {
      "t": 42611.194,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-31.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 124,
      "sourceType": "direct_entry"
    },
    {
      "t": 42617.728,
      "write": false,
      "project": "project-1",
      "language": "Prisma",
      "file": "file-14.prisma",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 344,
      "sourceType": "direct_entry"
    },
    {
      "t": 42624.438,
      "write": true,
      "project": "project-1",
      "language": "Prisma",
      "file": "file-14.prisma",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 344,
      "sourceType": "direct_entry"
    },
    {
      "t": 42685.904,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-30.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 113,
      "sourceType": "direct_entry"
    },
    {
      "t": 42706.966,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-31.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 124,
      "sourceType": "direct_entry"
    },
    {
      "t": 42883.226,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-31.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 124,
      "sourceType": "direct_entry"
    },
    {
      "t": 42963.897,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-31.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 124,
      "sourceType": "direct_entry"
    },
    {
      "t": 43028.44,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-31.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 124,
      "sourceType": "direct_entry"
    },
    {
      "t": 43122.391,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-31.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 124,
      "sourceType": "direct_entry"
    },
    {
      "t": 43153.074,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 43165.805,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 43177.151,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 43490.685,
      "write": false,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 43578.65,
      "write": false,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 43585.005,
      "write": false,
      "project": "project-1",
      "language": "CSS",
      "file": "file-32.css",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 164,
      "sourceType": "direct_entry"
    },
    {
      "t": 43650.224,
      "write": false,
      "project": "project-1",
      "language": "CSS",
      "file": "file-32.css",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 164,
      "sourceType": "direct_entry"
    },
    {
      "t": 43697.862,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 43708.403,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 43719.359,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 43835.195,
      "write": false,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 43922.719,
      "write": false,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 447,
      "sourceType": "direct_entry"
    },
    {
      "t": 43938.877,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-11.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 99,
      "sourceType": "direct_entry"
    },
    {
      "t": 43947.812,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-11.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 99,
      "sourceType": "direct_entry"
    },
    {
      "t": 44009.987,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-11.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 99,
      "sourceType": "direct_entry"
    },
    {
      "t": 44073.689,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-11.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 99,
      "sourceType": "direct_entry"
    },
    {
      "t": 44134.063,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-11.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 99,
      "sourceType": "direct_entry"
    },
    {
      "t": 44165.914,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-33.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 249,
      "sourceType": "direct_entry"
    },
    {
      "t": 44192.458,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-33.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 249,
      "sourceType": "direct_entry"
    },
    {
      "t": 44262.087,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-33.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 249,
      "sourceType": "direct_entry"
    },
    {
      "t": 44324.435,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-33.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 249,
      "sourceType": "direct_entry"
    },
    {
      "t": 44386.809,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-33.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 249,
      "sourceType": "direct_entry"
    },
    {
      "t": 44429.889,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-33.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 249,
      "sourceType": "direct_entry"
    },
    {
      "t": 44445.297,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-33.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 249,
      "sourceType": "direct_entry"
    },
    {
      "t": 44505.484,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-33.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 249,
      "sourceType": "direct_entry"
    },
    {
      "t": 44569.456,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-33.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 249,
      "sourceType": "direct_entry"
    },
    {
      "t": 44637.912,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-33.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 249,
      "sourceType": "direct_entry"
    },
    {
      "t": 44702.406,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-33.tsx",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 249,
      "sourceType": "direct_entry"
    },
    {
      "t": 44751.447,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-34.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 45,
      "sourceType": "direct_entry"
    },
    {
      "t": 44766.362,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-35.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 53,
      "sourceType": "direct_entry"
    },
    {
      "t": 44774.848,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-15.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 412,
      "sourceType": "direct_entry"
    },
    {
      "t": 44795.874,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-36.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 121,
      "sourceType": "direct_entry"
    },
    {
      "t": 44814.3,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 96,
      "sourceType": "direct_entry"
    },
    {
      "t": 44818.307,
      "write": true,
      "project": "project-1",
      "language": "JSON",
      "file": "file-22.json",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 75,
      "sourceType": "direct_entry"
    },
    {
      "t": 45021.662,
      "write": false,
      "project": "project-1",
      "language": "JSON",
      "file": "file-22.json",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 75,
      "sourceType": "direct_entry"
    },
    {
      "t": 45042.84,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-34.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 45,
      "sourceType": "direct_entry"
    },
    {
      "t": 45114.037,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-38.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 20,
      "sourceType": "direct_entry"
    },
    {
      "t": 45122.03,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-34.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 45,
      "sourceType": "direct_entry"
    },
    {
      "t": 45126.138,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-36.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 121,
      "sourceType": "direct_entry"
    },
    {
      "t": 45130.536,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-36.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 121,
      "sourceType": "direct_entry"
    },
    {
      "t": 45134.782,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-36.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 121,
      "sourceType": "direct_entry"
    },
    {
      "t": 45142.223,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 96,
      "sourceType": "direct_entry"
    },
    {
      "t": 45147.188,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 96,
      "sourceType": "direct_entry"
    },
    {
      "t": 45155.056,
      "write": false,
      "project": "project-1",
      "language": "Ignore List",
      "file": "file-39",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 49,
      "sourceType": "direct_entry"
    },
    {
      "t": 45159.418,
      "write": true,
      "project": "project-1",
      "language": "Ignore List",
      "file": "file-39",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 49,
      "sourceType": "direct_entry"
    },
    {
      "t": 45229.054,
      "write": false,
      "project": "project-1",
      "language": "Ignore List",
      "file": "file-39",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 49,
      "sourceType": "direct_entry"
    },
    {
      "t": 45454.261,
      "write": false,
      "project": "project-1",
      "language": "Ignore List",
      "file": "file-39",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 49,
      "sourceType": "direct_entry"
    },
    {
      "t": 45569.368,
      "write": false,
      "project": "project-1",
      "language": "Markdown",
      "file": "file-40.md",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 588,
      "sourceType": "direct_entry"
    },
    {
      "t": 45585.447,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 96,
      "sourceType": "direct_entry"
    },
    {
      "t": 45699.665,
      "write": false,
      "project": "project-1",
      "language": "Markdown",
      "file": "file-40.md",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 588,
      "sourceType": "direct_entry"
    },
    {
      "t": 45713.428,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 96,
      "sourceType": "direct_entry"
    },
    {
      "t": 45724.816,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 96,
      "sourceType": "direct_entry"
    },
    {
      "t": 45770.628,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 96,
      "sourceType": "direct_entry"
    },
    {
      "t": 45977.797,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 96,
      "sourceType": "direct_entry"
    },
    {
      "t": 45984.165,
      "write": false,
      "project": "project-1",
      "language": "Markdown",
      "file": "file-40.md",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 588,
      "sourceType": "direct_entry"
    },
    {
      "t": 46427.668,
      "write": false,
      "project": "project-1",
      "language": "Markdown",
      "file": "file-40.md",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 588,
      "sourceType": "direct_entry"
    },
    {
      "t": 46436.94,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 96,
      "sourceType": "direct_entry"
    },
    {
      "t": 46443.367,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 96,
      "sourceType": "direct_entry"
    },
    {
      "t": 46452.786,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 96,
      "sourceType": "direct_entry"
    },
    {
      "t": 46735.01,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 96,
      "sourceType": "direct_entry"
    },
    {
      "t": 46753.519,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-16.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 541,
      "sourceType": "direct_entry"
    },
    {
      "t": 46941.935,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-16.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 541,
      "sourceType": "direct_entry"
    },
    {
      "t": 46956.684,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 96,
      "sourceType": "direct_entry"
    },
    {
      "t": 46964.55,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 96,
      "sourceType": "direct_entry"
    },
    {
      "t": 47159.926,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 96,
      "sourceType": "direct_entry"
    },
    {
      "t": 47176.128,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-41",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 47257.253,
      "write": false,
      "project": "project-2",
      "language": "JavaScript",
      "file": "file-42.js",
      "category": "coding",
      "editor": "vscode",
      "lines": 180,
      "sourceType": "direct_entry"
    },
    {
      "t": 47284.549,
      "write": false,
      "project": "project-3",
      "language": null,
      "file": "file-43",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 47284.549,
      "write": false,
      "project": "project-3",
      "language": null,
      "file": "file-43",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 47284.549,
      "write": false,
      "project": "project-3",
      "language": "Bash",
      "file": "file-44",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 4,
      "sourceType": "direct_entry"
    },
    {
      "t": 47328.213,
      "write": false,
      "project": "project-3",
      "language": "JSON",
      "file": "file-22.json",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 14,
      "sourceType": "direct_entry"
    },
    {
      "t": 47400.313,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-45.ts",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 80,
      "sourceType": "direct_entry"
    },
    {
      "t": 47402.62,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-46.ts",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 62,
      "sourceType": "direct_entry"
    },
    {
      "t": 47458.332,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-47.ts",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 651,
      "sourceType": "direct_entry"
    },
    {
      "t": 47467.978,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-48.ts",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 103,
      "sourceType": "direct_entry"
    },
    {
      "t": 47477.549,
      "write": true,
      "project": "project-3",
      "language": "Bash",
      "file": "file-44",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 4,
      "sourceType": "direct_entry"
    },
    {
      "t": 47479.7,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-45.ts",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 79,
      "sourceType": "direct_entry"
    },
    {
      "t": 47481.549,
      "write": true,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 221,
      "sourceType": "direct_entry"
    },
    {
      "t": 47523.946,
      "write": false,
      "project": "project-3",
      "language": "Bash",
      "file": "file-44",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 5,
      "sourceType": "direct_entry"
    },
    {
      "t": 47532.549,
      "write": true,
      "project": "project-3",
      "language": "JSON",
      "file": "file-50.json",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 15,
      "sourceType": "direct_entry"
    },
    {
      "t": 47543.549,
      "write": true,
      "project": "project-3",
      "language": "JSON",
      "file": "file-50.json",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 15,
      "sourceType": "direct_entry"
    },
    {
      "t": 47548.549,
      "write": true,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 221,
      "sourceType": "direct_entry"
    },
    {
      "t": 47575.858,
      "write": true,
      "project": "project-3",
      "language": "Bash",
      "file": "file-44",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 5,
      "sourceType": "direct_entry"
    },
    {
      "t": 47582.439,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 221,
      "sourceType": "direct_entry"
    },
    {
      "t": 47643.549,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 221,
      "sourceType": "direct_entry"
    },
    {
      "t": 47688.527,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-51.output",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 47688.527,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-51.output",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 47733.271,
      "write": false,
      "project": "project-3",
      "language": "Dotenv",
      "file": "file-52.example",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 16,
      "sourceType": "direct_entry"
    },
    {
      "t": 47735.684,
      "write": false,
      "project": "project-3",
      "language": "Bash",
      "file": "file-44",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 4,
      "sourceType": "direct_entry"
    },
    {
      "t": 47737.734,
      "write": false,
      "project": "project-3",
      "language": "Dotenv",
      "file": "file-52.example",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 15,
      "sourceType": "direct_entry"
    },
    {
      "t": 47750.072,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-45.ts",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 79,
      "sourceType": "direct_entry"
    },
    {
      "t": 47751.592,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-46.ts",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 61,
      "sourceType": "direct_entry"
    },
    {
      "t": 47798.549,
      "write": true,
      "project": "project-3",
      "language": "JSON",
      "file": "file-22.json",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 33,
      "sourceType": "direct_entry"
    },
    {
      "t": 47801.746,
      "write": false,
      "project": "project-3",
      "language": "JSON",
      "file": "file-22.json",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 34,
      "sourceType": "direct_entry"
    },
    {
      "t": 47804.549,
      "write": true,
      "project": "project-3",
      "language": "JSON",
      "file": "file-50.json",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 14,
      "sourceType": "direct_entry"
    },
    {
      "t": 47815.462,
      "write": false,
      "project": "project-3",
      "language": "JSON",
      "file": "file-50.json",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 14,
      "sourceType": "direct_entry"
    },
    {
      "t": 47821.579,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 3,
      "sourceType": "direct_entry"
    },
    {
      "t": 47864.817,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 97,
      "sourceType": "direct_entry"
    },
    {
      "t": 47869.834,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 97,
      "sourceType": "direct_entry"
    },
    {
      "t": 47931.549,
      "write": false,
      "project": "project-3",
      "language": "JSON",
      "file": "file-50.json",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 14,
      "sourceType": "direct_entry"
    },
    {
      "t": 47957.129,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 97,
      "sourceType": "direct_entry"
    },
    {
      "t": 47977.67,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 449,
      "sourceType": "direct_entry"
    },
    {
      "t": 47988.831,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 449,
      "sourceType": "direct_entry"
    },
    {
      "t": 48009.92,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 449,
      "sourceType": "direct_entry"
    },
    {
      "t": 48231.549,
      "write": false,
      "project": "project-3",
      "language": "JSON",
      "file": "file-50.json",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 14,
      "sourceType": "direct_entry"
    },
    {
      "t": 48233.549,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 254,
      "sourceType": "direct_entry"
    },
    {
      "t": 48745.549,
      "write": true,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 254,
      "sourceType": "direct_entry"
    },
    {
      "t": 48745.549,
      "write": true,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 255,
      "sourceType": "direct_entry"
    },
    {
      "t": 48753.756,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 255,
      "sourceType": "direct_entry"
    },
    {
      "t": 48761.549,
      "write": true,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 255,
      "sourceType": "direct_entry"
    },
    {
      "t": 48836.549,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 255,
      "sourceType": "direct_entry"
    },
    {
      "t": 48836.549,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 97,
      "sourceType": "direct_entry"
    },
    {
      "t": 48840.688,
      "write": true,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "coding",
      "editor": "antigravityide",
      "lines": 222,
      "sourceType": "direct_entry"
    },
    {
      "t": 48903.217,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 97,
      "sourceType": "direct_entry"
    },
    {
      "t": 48908.129,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 97,
      "sourceType": "direct_entry"
    },
    {
      "t": 48981.165,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-37.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 97,
      "sourceType": "direct_entry"
    },
    {
      "t": 48981.165,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-41",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 49068.549,
      "write": false,
      "project": "project-3",
      "language": null,
      "file": "file-43",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 49086.549,
      "write": false,
      "project": "project-3",
      "language": null,
      "file": "file-43",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 49207.51,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-41",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 49223.878,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-41",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 49269.949,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-41",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 49279.712,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-41",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 49285.84,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-41",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 49285.84,
      "write": false,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 449,
      "sourceType": "direct_entry"
    },
    {
      "t": 49310.058,
      "write": true,
      "project": "project-1",
      "language": "HTML",
      "file": "file-2.html",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 449,
      "sourceType": "direct_entry"
    },
    {
      "t": 49341.161,
      "write": false,
      "project": "project-1",
      "language": null,
      "file": "file-41",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 50799.549,
      "write": false,
      "project": "project-3",
      "language": null,
      "file": "file-43",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 50801.549,
      "write": false,
      "project": "project-3",
      "language": null,
      "file": "file-43",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 51099.549,
      "write": false,
      "project": "project-3",
      "language": null,
      "file": "file-43",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 51101.549,
      "write": false,
      "project": "project-3",
      "language": null,
      "file": "file-43",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 0,
      "sourceType": "direct_entry"
    },
    {
      "t": 51101.549,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 222,
      "sourceType": "direct_entry"
    },
    {
      "t": 51524.549,
      "write": true,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 222,
      "sourceType": "direct_entry"
    },
    {
      "t": 51622.549,
      "write": true,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 222,
      "sourceType": "direct_entry"
    },
    {
      "t": 51648.549,
      "write": true,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 222,
      "sourceType": "direct_entry"
    },
    {
      "t": 51648.549,
      "write": true,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 318,
      "sourceType": "direct_entry"
    },
    {
      "t": 51770.321,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravityide",
      "lines": 319,
      "sourceType": "direct_entry"
    },
    {
      "t": 51788.154,
      "write": false,
      "project": "project-1",
      "language": "Markdown",
      "file": "file-13.md",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 278,
      "sourceType": "direct_entry"
    },
    {
      "t": 51794.895,
      "write": false,
      "project": "project-1",
      "language": "Markdown",
      "file": "file-13.md",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 278,
      "sourceType": "direct_entry"
    },
    {
      "t": 51795.549,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 318,
      "sourceType": "direct_entry"
    },
    {
      "t": 51846.396,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-53.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 93,
      "sourceType": "direct_entry"
    },
    {
      "t": 51885.719,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-16.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 541,
      "sourceType": "direct_entry"
    },
    {
      "t": 51887.549,
      "write": false,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 318,
      "sourceType": "direct_entry"
    },
    {
      "t": 51915.425,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-17.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 246,
      "sourceType": "direct_entry"
    },
    {
      "t": 51933.303,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-17.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 246,
      "sourceType": "direct_entry"
    },
    {
      "t": 51933.303,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-17.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 250,
      "sourceType": "direct_entry"
    },
    {
      "t": 51940.549,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-16.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 541,
      "sourceType": "direct_entry"
    },
    {
      "t": 51940.986,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-17.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 250,
      "sourceType": "direct_entry"
    },
    {
      "t": 51948.786,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-17.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 250,
      "sourceType": "direct_entry"
    },
    {
      "t": 52146.222,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-17.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 250,
      "sourceType": "direct_entry"
    },
    {
      "t": 52170.519,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-16.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 541,
      "sourceType": "direct_entry"
    },
    {
      "t": 52181.606,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-16.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 541,
      "sourceType": "direct_entry"
    },
    {
      "t": 52181.606,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-16.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 587,
      "sourceType": "direct_entry"
    },
    {
      "t": 52184.8,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-16.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 587,
      "sourceType": "direct_entry"
    },
    {
      "t": 52192.239,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-16.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 587,
      "sourceType": "direct_entry"
    },
    {
      "t": 52202.133,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-16.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 587,
      "sourceType": "direct_entry"
    },
    {
      "t": 52210.824,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-16.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 587,
      "sourceType": "direct_entry"
    },
    {
      "t": 52222.549,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-54.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 740,
      "sourceType": "direct_entry"
    },
    {
      "t": 52226.082,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-54.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 740,
      "sourceType": "direct_entry"
    },
    {
      "t": 52236.549,
      "write": true,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-55.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 141,
      "sourceType": "direct_entry"
    },
    {
      "t": 52236.549,
      "write": true,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-55.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 142,
      "sourceType": "direct_entry"
    },
    {
      "t": 52240.721,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-54.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 756,
      "sourceType": "direct_entry"
    },
    {
      "t": 52249.549,
      "write": true,
      "project": "project-3",
      "language": "TypeScript",
      "file": "file-49.ts",
      "category": "ai coding",
      "editor": "antigravity-ide",
      "lines": 318,
      "sourceType": "direct_entry"
    },
    {
      "t": 52251.043,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-54.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 756,
      "sourceType": "direct_entry"
    },
    {
      "t": 52258.864,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-54.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 756,
      "sourceType": "direct_entry"
    },
    {
      "t": 52266.196,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-54.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 756,
      "sourceType": "direct_entry"
    },
    {
      "t": 52279.543,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-54.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 756,
      "sourceType": "direct_entry"
    },
    {
      "t": 52284.757,
      "write": false,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-54.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 756,
      "sourceType": "direct_entry"
    },
    {
      "t": 52291.673,
      "write": true,
      "project": "project-1",
      "language": "TypeScript",
      "file": "file-54.ts",
      "category": "ai coding",
      "editor": "claude-code",
      "lines": 756,
      "sourceType": "direct_entry"
    }
  ]
};
